'use client'

import { useEffect, useRef, useState } from 'react'
import { Bot, Mic, Send, Volume2, X } from 'lucide-react'

type Message = { role: 'user' | 'assistant'; content: string }

export function NexusAIChat({ onClose, admin = false }: { onClose?: () => void; admin?: boolean }) {
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: admin ? 'Nexus Business Manager iko tayari. Naweza kusaidia catalog, orders, payments, classes, users na reports.' : 'Karibu Nexus. Naweza kusaidia games, classes, orders, live matches na account yako.' }])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [listening, setListening] = useState(false)
  const [voice, setVoice] = useState(true)
  const recognitionRef = useRef<{ stop: () => void } | null>(null)
  const send = async (text = input) => { const message = text.trim(); if (!message || loading) return; setInput(''); const next = [...messages, { role: 'user' as const, content: message }]; setMessages(next); setLoading(true); try { const response = await fetch('/api/ai/support', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message, history: next.slice(-8), admin }) }); const data = await response.json().catch(() => ({})); const reply = data.reply || (response.ok ? 'Samahani, sijapata jibu.' : 'AI haipatikani kwa sasa. Admin aangalie provider key, quota na billing.'); setMessages((current) => [...current, { role: 'assistant', content: reply }]); if (voice && 'speechSynthesis' in window) window.speechSynthesis.speak(new SpeechSynthesisUtterance(reply)) } catch { setMessages((current) => [...current, { role: 'assistant', content: 'Imeshindikana kuwasiliana na AI server. Jaribu tena.' }]) } finally { setLoading(false) } }
  const startVoice = () => { const browserWindow = window as typeof window & { SpeechRecognition?: new () => any; webkitSpeechRecognition?: new () => any }; const SpeechRecognitionAPI = browserWindow.SpeechRecognition || browserWindow.webkitSpeechRecognition; if (!SpeechRecognitionAPI) return setInput('Voice ya browser haipatikani; tumia Chrome au Edge.'); const recognition = new SpeechRecognitionAPI(); recognition.lang = 'sw-TZ'; recognition.interimResults = false; recognition.onresult = (event: any) => { const text = event.results[0][0].transcript; setInput(text); void send(text) }; recognition.onend = () => setListening(false); recognitionRef.current = recognition; setListening(true); recognition.start() }
  useEffect(() => () => { recognitionRef.current?.stop(); window.speechSynthesis?.cancel() }, [])
  return <section className={`nexus-chat ${admin ? 'nexus-chat-admin' : ''}`} role="dialog" aria-label={admin ? 'Private business manager' : 'Nexus AI support'}><header><div className="chat-avatar"><Bot size={17} /></div><div><b>{admin ? 'Private Business Manager' : 'Nexus AI support'}</b><small><span className="status-dot" /> Swahili + English</small></div>{onClose && <button className="icon-btn" aria-label="Close chat" onClick={onClose}><X size={17} /></button>}</header><div className="nexus-chat-messages">{messages.map((message, index) => <div className={`nexus-message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}{loading && <div className="nexus-message assistant">Nexus inaandika...</div>}</div><div className="chat-tools"><button type="button" className={voice ? 'active' : ''} onClick={() => setVoice(!voice)} aria-label="Toggle spoken replies"><Volume2 size={15} /></button><button type="button" className={listening ? 'active listening' : ''} onClick={startVoice} aria-label="Speak to Nexus"><Mic size={15} /></button><input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing && event.keyCode !== 229) void send() }} placeholder="Andika ujumbe..." /><button type="button" className="send-chat" onClick={() => void send()} aria-label="Send message"><Send size={15} /></button></div></section>
}
